put-object,sync created

diff --git a/bash-scripts/sync b/bash-scripts/sync
--- a/bash-scripts/sync
+++ b/bash-scripts/sync
@@ -1,3 +1,41 @@
 #!/usr/bin/env bash
 
-secret key - Kja3MJQZLXSgmKaUji2pIWUMDS2PgvY6kLPLVe/W
+#!/usr/bin/env bash
+set -e ## exit immediately if any line fails////
+directory="/workspace/AWS-Practicals/bash-scripts/rand_files"
+
+## remove folder if already exists
+rm -r $directory
+
+mkdir -p "$directory"
+chmod u+w "$directory"
+num_files=$(( ( RANDOM % 10 ) + 1 ))
+
+
+## bucket naming enter
+if [ $# -ne 1 ]; then
+    echo "Usage: $0 <bucket-name>"
+    exit 1
+fi
+
+BUCKET_NAME=$1
+
+
+for i in $(seq 1 $num_files); do
+
+  # Generate a random filename
+  filename=$(date +%s%N | sha256sum | base64 | head -c 10).txt
+  
+  # Generate random data
+  random_data=$(head /dev/urandom | base64 | head -c 100)
+
+  # Create the file with random content
+  echo "This is file number $i" > "$directory/$filename"
+  echo "Random data: $random_data" >> "$directory/$filename"
+  
+done
+
+echo "$num_files random files created in $directory"
+
+
+aws s3 sync $directory s3://$BUCKET_NAME
